{% set name = "asks" %}
{% set version = "2.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9db16bdf9fed8cae76db3b4365216ea2f1563b8ab9fe9a5e8e554177de61192

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - anyio
    - async_generator
    - h11

test:
  imports:
    - asks
  requires:
    - curio
    - overly
    - pytest

about:
  home: https://github.com/theelous3/asks
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENCE.txt
  summary: asks is an async requests-like http lib, for use in conjunction with the wonderful curio and trio async libs.
