{% set name = "asks" %}
{% set version = "2.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d67aecaa02d0c67fa761dfdb23854391e6996c6045fb9385b1f508b0956a190d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - async_generator
    - h11
    - multio >=0.2.3

test:
  imports:
    - asks
  requires:
    - curio
    - pytest
    - trio

about:
  home: https://github.com/theelous3/asks
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENCE.txt'
  summary: asks is an async requests-like http lib, for use in conjunction with the wonderful curio and trio async libs.

extra:
  recipe-maintainers:
    - CJ-Wright
