{% set name = "asks" %}
{% set version = "2.4.12" %}
{% set sha256 = "38de944eb350e7e4e3a918055fa8ff033da5f7b5ff385c1160a2d6b9d84783b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - anyio
    - async_generator
    - h11

test:
  requires:
    - curio
    - overly
    - pytest
  imports:
    - asks

about:
  home: https://github.com/theelous3/asks
  license: MIT
  license_family: MIT
  license_file: LICENCE.txt
  summary: asks is an async requests-like http lib, for use in conjunction with the wonderful curio and trio async libs.
